import fs from 'fs/promises';
import { compile } from 'json-schema-to-typescript';
import path from 'path';

async function generate() {
  const schemaPath = path.join(__dirname, 'protocol.schema.json');
  const outputPath = path.join(__dirname, 'types.ts');

  console.log('📖 Reading OpenClaw protocol schema...');
  const schemaData = JSON.parse(await fs.readFile(schemaPath, 'utf-8'));

  console.log('🔧 Generating TypeScript types...');

  const options = {
    bannerComment: '/* Auto-generated from OpenClaw protocol schema */\n/* Do not edit manually */',
    style: {
      singleQuote: true,
    },
    unknownAny: false,
    enableConstEnums: false,
    additionalProperties: false,
  };

  let output = options.bannerComment + '\n\n';

  // Generate types for the root schema (RequestFrame, ResponseFrame, EventFrame)
  console.log('  - Generating root protocol types...');
  const rootTypes = await compile(schemaData, 'OpenClawProtocol', {
    ...options,
    bannerComment: '',
  });
  output += rootTypes + '\n';

  // Generate types for all definitions
  if (schemaData.definitions) {
    console.log(`  - Generating ${Object.keys(schemaData.definitions).length} definition types...`);

    for (const [name, definition] of Object.entries(schemaData.definitions)) {
      // Skip if already generated by root (RequestFrame, ResponseFrame, EventFrame)
      if (['RequestFrame', 'ResponseFrame', 'EventFrame'].includes(name)) {
        continue;
      }

      try {
        const defTypes = await compile(
          definition as any,
          name,
          {
            ...options,
            bannerComment: '',
          }
        );
        output += defTypes + '\n';
      } catch (error) {
        console.warn(`    ⚠️  Skipped ${name}:`, (error as Error).message);
      }
    }
  }

  console.log('💾 Writing types to', outputPath);
  await fs.writeFile(outputPath, output);

  console.log('✅ Generated OpenClaw types successfully!');
  console.log(`   Total definitions processed: ${Object.keys(schemaData.definitions || {}).length}`);
}

generate().catch((error) => {
  console.error('❌ Failed to generate types:', error);
  process.exit(1);
});
